const CONSTAPI = {
	//添加家政人员
	addWorker:{
		url:"/worker",
		method:"POST"
	},
	//更新家政人员
	putWorker:{
		url:'/worker/profile',
		method:'PUT'
	},
	// 上传证件
	postCertificate:{
		url:'/worker/profile/certificate',
		method:'POST'
	},
	//获取证件列表
	certificateList:{
		url:'/worker/profile/certificate/list',
		method:'GET'
	},
	//更新证件
	putCertificate:{
		url:'/worker/profile/certificate/update',
		method:'POST'
	},
	//删除证件
	deleteCertificate:{
		url:"/worker/profile/certificate",
		method:'DELETE'
	},
	//新增工作经历
	addWorkExpericence:{
		url:'/worker/profile/work/experience',
		method:'POST'
	},
	workExpericenceList:{
		url:'/worker/profile/work/experience/list',
		method:'GET'
	},
	//更新工作经历
	putEx:{
		url:'/worker/profile/work/experience',
		method:'PUT'
		
	},
	//删除工作经历
	deleteEx:{
		url:'/worker/profile/work/experience',
		method:"DELETE"
	},
	//新增家庭成员
	addFamily:{
		url:'/worker/profile/family/member',
		method:'POST'
	},
	familyList:{
		url:"/worker/profile/family/member/list",
		method:'GET'
	},
	//更新家庭成员
	putFamilyPeople:{
		url:'/worker/profile/family/member',
		method:'PUT'
	},
	//删除家庭成员
	deleteFamily:{
		url:'/worker/profile/family/member',
		method:"DELETE"
	},
	//服务员列表
	wokerList:{
		url:'/worker/list/paging',
		method:'GET'
	},
	//服务员详情
	wokerDetail:{
		url:"/worker/profile",
		method:'GET'
	},
	//新增图片
	postPoto:{
		url:'/worker/profile/photo',
		method:'POST'
	},
	//更新图片(没有)
	putPoto:{
		url:''
	},
	//删除照片
	deletePhoto:{
		url:'/worker/profile/photo',
		method:"DELETE"
	},
	photoList:{
		url:'/worker/profile/photo/list',
		method:'GET'
	},
	//上传背景调查
	profileBackgroung:{
		url:'/worker/profile/background_check',
		method:"POST"
	},
	//背景调查列表
	backgroundList:{
		url:'/worker/profile/background_check/list',
		method:"GET"
	},
	//删除背景调查
	deleteBg:{
		url:'/worker/profile/background_check',
		method:"DELETE"
	},
	// 上传证件图片
	newPostCertificate:{
		url:'/worker/profile/certificate/image',
		method:"POST"
	},
	//更新证件
	newPutCertificate:{
		url:'/worker/profile/certificate',
		method:'PUT'
	},
	//创建能力
	addAbility:{
		url:'/worker/profile/ability',
		method:"POST"
	},
	//获取能力
	abilityList:{
		url:"/worker/profile/ability",
		method:"GET"
	},
	//更新能力
	putAbility:{
		url:"/worker/profile/ability",
		method:"PUT"
	},
	deleteAbility:{
		url:'/worker/profile/ability',
		method:"DELETE"
	},
	//创建数据
	addData:{
		url:"/worker/profile/data",
		method:"POST"
	},
	//获取数据
	dataDetail:{
		url:'/worker/profile/data',
		method:'GET'
	},
	//更新数据
	putData:{
		url:'/worker/profile/data',
		method:"PUT"
	},
	//删除数据
	deleteData:{
		url:'/worker/profile/data',
		method:"DELETE"
	},
	//创建接单意向
	addJobExpectation:{
		url:"/worker/profile/job/expectation",
		method:'POST'
	},
	//接单意向列表
	jobExDetail:{
		url:'/worker/profile/job/expectation',
		method:'GET'
	},
	deleteJobEx:{
		url:'/worker/profile/job/expectation',
		method:"DELETE"
	},
	//更新
	putJobEx:{
		url:'/worker/profile/job/expectation',
		method:'PUT'
	},
	searchWorker:{
		url:'/worker/search',
		method:'POST'
	}
}
export default CONSTAPI